name: fbs-compose

networks:
  fbs_net:
    name: fbs-net

services:
  fbs:
    container_name: fbs
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - fbs_net
    ports:
      - "8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__SqlServer=Data Source=db,1433;Initial Catalog=adonet-fbs;User ID=sa;Password=${DB_SA_PASSWORD};TrustServerCertificate=True;
  db:
    container_name: fbs-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 14333:1433
    networks:
      - fbs_net
    volumes:
      - ./Web/sql-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./volumes/mssql/backups:/var/opt/mssql/backups
      - ./volumes/mssql/data:/var/opt/mssql/data
      - ./volumes/mssql/log:/var/opt/mssql/log
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - MSSQL_SA_PASSWORD=${DB_SA_PASSWORD}
      - MSSQL_BACKUP_DIR=/var/opt/mssql/backups
  nginx:
    image: nginx:latest
    container_name: fbs-proxy
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - fbs
    networks:
      - fbs_net

