name: fbs-compose

networks:
  fbs_net:
    name: fbs-net

services:
  fbs:
    container_name: fbs
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    networks:
      - fbs_net
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__SqlServer=Data Source=db,1433;Initial Catalog=adonet-fbs;User ID=sa;Password=${DB_SA_PASSWORD};TrustServerCertificate=True;
  db:
    container_name: fbs-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 14333:1433
    networks:
      - fbs_net
    volumes:
      - ./mssql/backups:/var/opt/mssql/backups
      - ./mssql/data:/var/opt/mssql/data
      - ./mssql/log:/var/opt/mssql/log
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - MSSQL_SA_PASSWORD=${DB_SA_PASSWORD}
      - MSSQL_BACKUP_DIR=/var/opt/mssql/backups
  nginx:
    image: nginx:latest
    container_name: fbs-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - fbs
    networks:
      - fbs_net
    restart: always

